//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empolyee
    {
        public int Employee_ID { get; set; }
        public string Empolyee_Name { get; set; }
        public string Employee_Phone { get; set; }
        public string Employee_Address { get; set; }
    }
}
